#!/usr/bin/env python3

import sys

import jmcomic

args = sys.argv[1:]

option = jmcomic.JmOption.construct(
    {
        "dir_rule": {"base_dir": "/Volumes/Quasar/comic/jm"},
        "download": {"image": {"suffix": ".jpg"}},
        "plugins": {
            "after_album": [
                {
                    "plugin": "long_img",
                    "kwargs": {
                        "img_dir": "/Volumes/Quasar/comic/jm",
                        "filename_rule": "Aname",
                    },
                }
            ]
        },
    },
    cover_default=True,
)

for arg in args:
    print("Downloading %s..." % arg)
    jmcomic.download_album(arg, option)

print("All downloads finished")
