#!/usr/bin/env python3

import hashlib
import shutil
from pathlib import Path

music = Path.home() / "Music" / "Music" / "spotdl"
dst = Path("/Volumes/Quasar/music")

extensions = (".mp3", ".m4a")
check_exts = lambda m: m.suffix in extensions

if not music.exists():
    print("Error: Music directory not found")
    exit(1)

if not dst.exists():
    print("Error: Destination directory not found")
    exit(1)

try:
    with open(dst / "hashes", "br") as f:
        hashes = eval(f.read().decode())
except FileNotFoundError:
    hashes = {}

new_hashes = {}
for file in filter(check_exts, music.glob("*")):
    if (
        file.name in hashes
        and hashes[file.name] == hashlib.md5(file.read_bytes()).hexdigest()
        and (dst / file.name).exists()
    ):
        print(f"Skipping {file.name}")
        new_hashes[file.name] = hashes[file.name]
        continue
    print(f"Copying {file.name}")
    shutil.copy(file, dst)
    new_hashes[file.name] = hashlib.md5(file.read_bytes()).hexdigest()

with open(dst / "hashes", "bw") as f:
    f.write(str(new_hashes).encode())
